# Generated by Django 4.1.1 on 2022-09-25 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_email_alter_interview_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='post_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='interview',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 15, 19, 8, 414351)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 15, 19, 8, 414339)),
        ),
    ]
